//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Behaviac.Design.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Behaviac.Design.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About  的本地化字符串。
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Action Name 的本地化字符串。
        /// </summary>
        internal static string ActionName {
            get {
                return ResourceManager.GetString("ActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Action Result 的本地化字符串。
        /// </summary>
        internal static string ActionResult {
            get {
                return ResourceManager.GetString("ActionResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Enum 的本地化字符串。
        /// </summary>
        internal static string AddEnum {
            get {
                return ResourceManager.GetString("AddEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Enum Member 的本地化字符串。
        /// </summary>
        internal static string AddEnumMember {
            get {
                return ResourceManager.GetString("AddEnumMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Event 的本地化字符串。
        /// </summary>
        internal static string AddEvent {
            get {
                return ResourceManager.GetString("AddEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Local Variable 的本地化字符串。
        /// </summary>
        internal static string AddLocalProperty {
            get {
                return ResourceManager.GetString("AddLocalProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Method 的本地化字符串。
        /// </summary>
        internal static string AddMethod {
            get {
                return ResourceManager.GetString("AddMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Property 的本地化字符串。
        /// </summary>
        internal static string AddProperty {
            get {
                return ResourceManager.GetString("AddProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Struct 的本地化字符串。
        /// </summary>
        internal static string AddStruct {
            get {
                return ResourceManager.GetString("AddStruct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Struct Member 的本地化字符串。
        /// </summary>
        internal static string AddStructMember {
            get {
                return ResourceManager.GetString("AddStructMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Task 的本地化字符串。
        /// </summary>
        internal static string AddTask {
            get {
                return ResourceManager.GetString("AddTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Type 的本地化字符串。
        /// </summary>
        internal static string AddType {
            get {
                return ResourceManager.GetString("AddType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} in {1} is not derived from or the same as or does not inherit {2} in {3}. Please try another behavior file again! 的本地化字符串。
        /// </summary>
        internal static string AgentErrorInfo {
            get {
                return ResourceManager.GetString("AgentErrorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 all 的本地化字符串。
        /// </summary>
        internal static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Analyze... 的本地化字符串。
        /// </summary>
        internal static string AnalyzeDump {
            get {
                return ResourceManager.GetString("AnalyzeDump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Analyze Log File... 的本地化字符串。
        /// </summary>
        internal static string AnalyzeLog {
            get {
                return ResourceManager.GetString("AnalyzeLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Backward {
            get {
                object obj = ResourceManager.GetObject("Backward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Behaviac Designer 的本地化字符串。
        /// </summary>
        internal static string BehaviacDesigner {
            get {
                return ResourceManager.GetString("BehaviacDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Behavior Error 的本地化字符串。
        /// </summary>
        internal static string BehaviorError {
            get {
                return ResourceManager.GetString("BehaviorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Behavior Filename 的本地化字符串。
        /// </summary>
        internal static string BehaviorFilename {
            get {
                return ResourceManager.GetString("BehaviorFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Behaviors 的本地化字符串。
        /// </summary>
        internal static string BehaviorGroupName {
            get {
                return ResourceManager.GetString("BehaviorGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide all breakpoints in the view. 的本地化字符串。
        /// </summary>
        internal static string BreakpointsHide {
            get {
                return ResourceManager.GetString("BreakpointsHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show all breakpoints in the view. 的本地化字符串。
        /// </summary>
        internal static string BreakpointsShow {
            get {
                return ResourceManager.GetString("BreakpointsShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tree Exec Stack 的本地化字符串。
        /// </summary>
        internal static string Callstack {
            get {
                return ResourceManager.GetString("Callstack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The current added behavior will be circular referenced.
        ///Are your sure add it? 的本地化字符串。
        /// </summary>
        internal static string CircularReferencedInfo {
            get {
                return ResourceManager.GetString("CircularReferencedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to clear all generated code files on the folder &quot;{0}&quot; ? 的本地化字符串。
        /// </summary>
        internal static string ClearGeneratedCodesInfo {
            get {
                return ResourceManager.GetString("ClearGeneratedCodesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap connect {
            get {
                object obj = ResourceManager.GetObject("connect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Connect Server 的本地化字符串。
        /// </summary>
        internal static string ConnectServer {
            get {
                return ResourceManager.GetString("ConnectServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon crashdump {
            get {
                object obj = ResourceManager.GetObject("crashdump", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Double-click an Instance to Debug 的本地化字符串。
        /// </summary>
        internal static string DebugOperation {
            get {
                return ResourceManager.GetString("DebugOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete All Breakpoints 的本地化字符串。
        /// </summary>
        internal static string DeleteAllBreakpoints {
            get {
                return ResourceManager.GetString("DeleteAllBreakpoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure to delete all breakpoints? 的本地化字符串。
        /// </summary>
        internal static string DeleteAllBreakpointsWarning {
            get {
                return ResourceManager.GetString("DeleteAllBreakpointsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure to delete the selected breakpoints? 的本地化字符串。
        /// </summary>
        internal static string DeleteBreakpointsWarning {
            get {
                return ResourceManager.GetString("DeleteBreakpointsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure delete the selected bevavior folder &quot;{0}&quot;? 的本地化字符串。
        /// </summary>
        internal static string DeleteFolderWarningInfo {
            get {
                return ResourceManager.GetString("DeleteFolderWarningInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Selected Breakpoints 的本地化字符串。
        /// </summary>
        internal static string DeleteSelectedBreakpoints {
            get {
                return ResourceManager.GetString("DeleteSelectedBreakpoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Warning 的本地化字符串。
        /// </summary>
        internal static string DeleteWarning {
            get {
                return ResourceManager.GetString("DeleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure delete the selected bevavior file &quot;{0}&quot;? 的本地化字符串。
        /// </summary>
        internal static string DeleteWarningInfo {
            get {
                return ResourceManager.GetString("DeleteWarningInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        internal static string DesignerError {
            get {
                return ResourceManager.GetString("DesignerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Design 的本地化字符串。
        /// </summary>
        internal static string DesignerTabName {
            get {
                return ResourceManager.GetString("DesignerTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The folder &quot;{0}&quot; has existed. Please input another name! 的本地化字符串。
        /// </summary>
        internal static string DirectoryWarningInfo {
            get {
                return ResourceManager.GetString("DirectoryWarningInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disable 的本地化字符串。
        /// </summary>
        internal static string DisableNode {
            get {
                return ResourceManager.GetString("DisableNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap disconnect {
            get {
                object obj = ResourceManager.GetObject("disconnect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Disconnect Server 的本地化字符串。
        /// </summary>
        internal static string DisconnectServer {
            get {
                return ResourceManager.GetString("DisconnectServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap document_new {
            get {
                object obj = ResourceManager.GetObject("document_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Enum 的本地化字符串。
        /// </summary>
        internal static string EditEnum {
            get {
                return ResourceManager.GetString("EditEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Enum Member 的本地化字符串。
        /// </summary>
        internal static string EditEnumMember {
            get {
                return ResourceManager.GetString("EditEnumMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Event 的本地化字符串。
        /// </summary>
        internal static string EditEvent {
            get {
                return ResourceManager.GetString("EditEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Local Variable 的本地化字符串。
        /// </summary>
        internal static string EditLocalProperty {
            get {
                return ResourceManager.GetString("EditLocalProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Method 的本地化字符串。
        /// </summary>
        internal static string EditMethod {
            get {
                return ResourceManager.GetString("EditMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Par 的本地化字符串。
        /// </summary>
        internal static string EditPar {
            get {
                return ResourceManager.GetString("EditPar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Cusom Property 的本地化字符串。
        /// </summary>
        internal static string EditProperty {
            get {
                return ResourceManager.GetString("EditProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Struct 的本地化字符串。
        /// </summary>
        internal static string EditStruct {
            get {
                return ResourceManager.GetString("EditStruct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Struct Member 的本地化字符串。
        /// </summary>
        internal static string EditStructMember {
            get {
                return ResourceManager.GetString("EditStructMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Task 的本地化字符串。
        /// </summary>
        internal static string EditTask {
            get {
                return ResourceManager.GetString("EditTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Type 的本地化字符串。
        /// </summary>
        internal static string EditType {
            get {
                return ResourceManager.GetString("EditType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The meta info may be not loaded. Please check it! 的本地化字符串。
        /// </summary>
        internal static string EmptyMetaWarning {
            get {
                return ResourceManager.GetString("EmptyMetaWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable 的本地化字符串。
        /// </summary>
        internal static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable or disable itself 的本地化字符串。
        /// </summary>
        internal static string EnableDesc {
            get {
                return ResourceManager.GetString("EnableDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable 的本地化字符串。
        /// </summary>
        internal static string EnableNode {
            get {
                return ResourceManager.GetString("EnableNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 enter 的本地化字符串。
        /// </summary>
        internal static string enter {
            get {
                return ResourceManager.GetString("enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please set the right name for the enum member. 的本地化字符串。
        /// </summary>
        internal static string EnumMemberVerifyWarning {
            get {
                return ResourceManager.GetString("EnumMemberVerifyWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error Check 的本地化字符串。
        /// </summary>
        internal static string ErrorCheck {
            get {
                return ResourceManager.GetString("ErrorCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Information 的本地化字符串。
        /// </summary>
        internal static string ErrorList {
            get {
                return ResourceManager.GetString("ErrorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The count of the parameters of the event can not be more than 3. 的本地化字符串。
        /// </summary>
        internal static string EventParametersInfo {
            get {
                return ResourceManager.GetString("EventParametersInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Plugin could not be loaded as it does not contain the type {0}. 的本地化字符串。
        /// </summary>
        internal static string ExceptionCouldNotLoadPlugin {
            get {
                return ResourceManager.GetString("ExceptionCouldNotLoadPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The node could not be extracted. Please check with Node.ParentCanAdoptChildren 的本地化字符串。
        /// </summary>
        internal static string ExceptionNodeCouldNotBeExtracted {
            get {
                return ResourceManager.GetString("ExceptionNodeCouldNotBeExtracted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The file {0} does not exist. 的本地化字符串。
        /// </summary>
        internal static string ExceptionNoSuchFile {
            get {
                return ResourceManager.GetString("ExceptionNoSuchFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 exit 的本地化字符串。
        /// </summary>
        internal static string exit {
            get {
                return ResourceManager.GetString("exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hold Ctrl to click to expand/collapse all children of the current node. 的本地化字符串。
        /// </summary>
        internal static string ExpandAllInfo {
            get {
                return ResourceManager.GetString("ExpandAllInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Interrupt Condition : Click here to expand or collapse the attached condition node. 的本地化字符串。
        /// </summary>
        internal static string ExpandConnectorInfo {
            get {
                return ResourceManager.GetString("ExpandConnectorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap export {
            get {
                object obj = ResourceManager.GetObject("export", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 The {0} cannot be exported, because it contains some errors. Please check errors for this behavior firstly! 的本地化字符串。
        /// </summary>
        internal static string ExportBehaviorError {
            get {
                return ResourceManager.GetString("ExportBehaviorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Behaviors to Export: 的本地化字符串。
        /// </summary>
        internal static string ExportBehaviors {
            get {
                return ResourceManager.GetString("ExportBehaviors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Error 的本地化字符串。
        /// </summary>
        internal static string ExportError {
            get {
                return ResourceManager.GetString("ExportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} exported file(s), {1} invalid file(s) 的本地化字符串。
        /// </summary>
        internal static string ExportFileCountInfo {
            get {
                return ResourceManager.GetString("ExportFileCountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 types are genereated at &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string ExportMessages {
            get {
                return ResourceManager.GetString("ExportMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export Warning 的本地化字符串。
        /// </summary>
        internal static string ExportWarning {
            get {
                return ResourceManager.GetString("ExportWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There are some warnings in the current behavior file.
        ///
        ///Yes : Export it anyway.
        ///No : Check the warnings. 的本地化字符串。
        /// </summary>
        internal static string ExportWarningInfo {
            get {
                return ResourceManager.GetString("ExportWarningInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 failure 的本地化字符串。
        /// </summary>
        internal static string failure {
            get {
                return ResourceManager.GetString("failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Behaviors with Errors: 的本地化字符串。
        /// </summary>
        internal static string FaultBehaviors {
            get {
                return ResourceManager.GetString("FaultBehaviors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap File_Delete {
            get {
                object obj = ResourceManager.GetObject("File_Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap File_Open {
            get {
                object obj = ResourceManager.GetObject("File_Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似  file(s) 的本地化字符串。
        /// </summary>
        internal static string FileCountInfo {
            get {
                return ResourceManager.GetString("FileCountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Error 的本地化字符串。
        /// </summary>
        internal static string FileError {
            get {
                return ResourceManager.GetString("FileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Modified but not Exported 的本地化字符串。
        /// </summary>
        internal static string FileModified {
            get {
                return ResourceManager.GetString("FileModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The behavior file {0} might be modified.
        ///Please reexport it and relaunch the game, otherwise it might be abnormal! 的本地化字符串。
        /// </summary>
        internal static string FileModifiedInfo {
            get {
                return ResourceManager.GetString("FileModifiedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The behavior filename can only be ascii character with a-z, A-Z, 0-9 and _! 的本地化字符串。
        /// </summary>
        internal static string FilenameWarning {
            get {
                return ResourceManager.GetString("FilenameWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The filename &quot;{0}&quot; has existed. Please input another name! 的本地化字符串。
        /// </summary>
        internal static string FilenameWarningInfo {
            get {
                return ResourceManager.GetString("FilenameWarningInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Warning 的本地化字符串。
        /// </summary>
        internal static string FileWarning {
            get {
                return ResourceManager.GetString("FileWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find All 的本地化字符串。
        /// </summary>
        internal static string FindAll {
            get {
                return ResourceManager.GetString("FindAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find Next 的本地化字符串。
        /// </summary>
        internal static string FindNext {
            get {
                return ResourceManager.GetString("FindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find Results 的本地化字符串。
        /// </summary>
        internal static string FindResults {
            get {
                return ResourceManager.GetString("FindResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find all: &quot;{0}&quot;,  Matching nodes: {1},  Matching files: {2},  Total files searched: {3} 的本地化字符串。
        /// </summary>
        internal static string FindResultsInfo {
            get {
                return ResourceManager.GetString("FindResultsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Find Result 的本地化字符串。
        /// </summary>
        internal static string FindWarning {
            get {
                return ResourceManager.GetString("FindWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not found! 的本地化字符串。
        /// </summary>
        internal static string FindWarningInfo {
            get {
                return ResourceManager.GetString("FindWarningInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap folder_new {
            get {
                object obj = ResourceManager.GetObject("folder_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Folder_Open {
            get {
                object obj = ResourceManager.GetObject("Folder_Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Forward {
            get {
                object obj = ResourceManager.GetObject("Forward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Hit Count 的本地化字符串。
        /// </summary>
        internal static string HitCount {
            get {
                return ResourceManager.GetString("HitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Incompatible Workspace 的本地化字符串。
        /// </summary>
        internal static string IncompatibleWorkspace {
            get {
                return ResourceManager.GetString("IncompatibleWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The path for the generated type is empty, so please go to the Edit Workspace dialog to set it. 的本地化字符串。
        /// </summary>
        internal static string InvalidExportedTypePath {
            get {
                return ResourceManager.GetString("InvalidExportedTypePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 will the class file be generated?
        ///    If so, the class files will be generated, please set the header files if the language is C++.
        ///    otherwise, the class file will not be generated.
        ///   的本地化字符串。
        /// </summary>
        internal static string IsTypeImplemented {
            get {
                return ResourceManager.GetString("IsTypeImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The language setting will take effect when the editor is launched next time. 的本地化字符串。
        /// </summary>
        internal static string LanguageChangedWarning {
            get {
                return ResourceManager.GetString("LanguageChangedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your version {0} is the latest already. 的本地化字符串。
        /// </summary>
        internal static string LatestVersionInfo {
            get {
                return ResourceManager.GetString("LatestVersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The layout of the editor will be reset. Are you sure? 的本地化字符串。
        /// </summary>
        internal static string LayoutResetWarning {
            get {
                return ResourceManager.GetString("LayoutResetWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load Error 的本地化字符串。
        /// </summary>
        internal static string LoadError {
            get {
                return ResourceManager.GetString("LoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Load Warning 的本地化字符串。
        /// </summary>
        internal static string LoadWarning {
            get {
                return ResourceManager.GetString("LoadWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to load the workspace file {0}! 的本地化字符串。
        /// </summary>
        internal static string LoadWorkspaceError {
            get {
                return ResourceManager.GetString("LoadWorkspaceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close {0} 的本地化字符串。
        /// </summary>
        internal static string Menu_CloseBehavior {
            get {
                return ResourceManager.GetString("Menu_CloseBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        internal static string Menu_CloseBehavior_Default {
            get {
                return ResourceManager.GetString("Menu_CloseBehavior_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export {0}... 的本地化字符串。
        /// </summary>
        internal static string Menu_ExportBehavior {
            get {
                return ResourceManager.GetString("Menu_ExportBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export... 的本地化字符串。
        /// </summary>
        internal static string Menu_ExportBehavior_Default {
            get {
                return ResourceManager.GetString("Menu_ExportBehavior_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save {0} 的本地化字符串。
        /// </summary>
        internal static string Menu_SaveBehavior {
            get {
                return ResourceManager.GetString("Menu_SaveBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string Menu_SaveBehavior_Default {
            get {
                return ResourceManager.GetString("Menu_SaveBehavior_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save {0} As... 的本地化字符串。
        /// </summary>
        internal static string Menu_SaveBehaviorAs {
            get {
                return ResourceManager.GetString("Menu_SaveBehaviorAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save As... 的本地化字符串。
        /// </summary>
        internal static string Menu_SaveBehaviorAs_Default {
            get {
                return ResourceManager.GetString("Menu_SaveBehaviorAs_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Behavior Trees Exportd: {0} 的本地化字符串。
        /// </summary>
        internal static string MessageBTExport {
            get {
                return ResourceManager.GetString("MessageBTExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Messages 的本地化字符串。
        /// </summary>
        internal static string MessageOutput {
            get {
                return ResourceManager.GetString("MessageOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The meta data has been modified, so do you want to save it? 的本地化字符串。
        /// </summary>
        internal static string MetaSaveInfo {
            get {
                return ResourceManager.GetString("MetaSaveInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Types Browser 的本地化字符串。
        /// </summary>
        internal static string MetaStore {
            get {
                return ResourceManager.GetString("MetaStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The workspace file will be updated and the meta file will not be used any longer.
        ///You should export all files with the latest designer.
        ///更多详情请参考：https://www.behaviac.com/language/zh/updatenotes/#36x 的本地化字符串。
        /// </summary>
        internal static string MetaWarning {
            get {
                return ResourceManager.GetString("MetaWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The count of the parameters of the method can not be more than 8. 的本地化字符串。
        /// </summary>
        internal static string MethodParametersInfo {
            get {
                return ResourceManager.GetString("MethodParametersInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please set the right name, return type and parameters for the method. 的本地化字符串。
        /// </summary>
        internal static string MethodVerifyWarning {
            get {
                return ResourceManager.GetString("MethodVerifyWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This member has already been used.
        ///Are you sure to continue? 的本地化字符串。
        /// </summary>
        internal static string ModifyMemberWarning {
            get {
                return ResourceManager.GetString("ModifyMemberWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This type has already been used.
        ///Are you sure to continue? 的本地化字符串。
        /// </summary>
        internal static string ModifyTypeWarning {
            get {
                return ResourceManager.GetString("ModifyTypeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Behavior 的本地化字符串。
        /// </summary>
        internal static string NewBehavior {
            get {
                return ResourceManager.GetString("NewBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Newer Version Found 的本地化字符串。
        /// </summary>
        internal static string NewerVersionFound {
            get {
                return ResourceManager.GetString("NewerVersionFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Newer Version {0} is available, download it?
        ///
        ///{1} 的本地化字符串。
        /// </summary>
        internal static string NewerVersionInfo {
            get {
                return ResourceManager.GetString("NewerVersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Par 的本地化字符串。
        /// </summary>
        internal static string NewPar {
            get {
                return ResourceManager.GetString("NewPar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Prefab 的本地化字符串。
        /// </summary>
        internal static string NewPrefab {
            get {
                return ResourceManager.GetString("NewPrefab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No such behavior: {0} {1} 的本地化字符串。
        /// </summary>
        internal static string NoBehaviorInfo {
            get {
                return ResourceManager.GetString("NoBehaviorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Node Id 的本地化字符串。
        /// </summary>
        internal static string NodeId {
            get {
                return ResourceManager.GetString("NodeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Node Type 的本地化字符串。
        /// </summary>
        internal static string NodeType {
            get {
                return ResourceManager.GetString("NodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Normal Mode [Alt to Pan Mode] : Middle drag to pan, middle wheel to scale 的本地化字符串。
        /// </summary>
        internal static string NormalMode {
            get {
                return ResourceManager.GetString("NormalMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You should create or load a workspace firstly! 的本地化字符串。
        /// </summary>
        internal static string NullWorkspace {
            get {
                return ResourceManager.GetString("NullWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Log or Dump File 的本地化字符串。
        /// </summary>
        internal static string OpenDumpFile {
            get {
                return ResourceManager.GetString("OpenDumpFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Log File 的本地化字符串。
        /// </summary>
        internal static string OpenLogFile {
            get {
                return ResourceManager.GetString("OpenLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Prefab 的本地化字符串。
        /// </summary>
        internal static string OpenPrefab {
            get {
                return ResourceManager.GetString("OpenPrefab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Reference 的本地化字符串。
        /// </summary>
        internal static string OpenReference {
            get {
                return ResourceManager.GetString("OpenReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operand1 的本地化字符串。
        /// </summary>
        internal static string Operand1 {
            get {
                return ResourceManager.GetString("Operand1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operand2 的本地化字符串。
        /// </summary>
        internal static string Operand2 {
            get {
                return ResourceManager.GetString("Operand2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operand1 的本地化字符串。
        /// </summary>
        internal static string OperandDesc1 {
            get {
                return ResourceManager.GetString("OperandDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operand2 的本地化字符串。
        /// </summary>
        internal static string OperandDesc2 {
            get {
                return ResourceManager.GetString("OperandDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Output 的本地化字符串。
        /// </summary>
        internal static string Output {
            get {
                return ResourceManager.GetString("Output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pan Mode [Alt to Normal Mode] : Left drag to pan, right drag to scale 的本地化字符串。
        /// </summary>
        internal static string PanMode {
            get {
                return ResourceManager.GetString("PanMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Par {0} in {1} already exists in {2}. Please try another prefab file again! 的本地化字符串。
        /// </summary>
        internal static string ParErrorInfo {
            get {
                return ResourceManager.GetString("ParErrorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pars 的本地化字符串。
        /// </summary>
        internal static string Pars {
            get {
                return ResourceManager.GetString("Pars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pars of {0} 的本地化字符串。
        /// </summary>
        internal static string ParsOf {
            get {
                return ResourceManager.GetString("ParsOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Par Warning 的本地化字符串。
        /// </summary>
        internal static string ParWarning {
            get {
                return ResourceManager.GetString("ParWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The par name &quot;{0}&quot; already exists.
        ///Please input another one. 的本地化字符串。
        /// </summary>
        internal static string ParWarningInfo {
            get {
                return ResourceManager.GetString("ParWarningInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Pause {
            get {
                object obj = ResourceManager.GetObject("Pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Play {
            get {
                object obj = ResourceManager.GetObject("Play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Plugin Error 的本地化字符串。
        /// </summary>
        internal static string PluginError {
            get {
                return ResourceManager.GetString("PluginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon prefab {
            get {
                object obj = ResourceManager.GetObject("prefab", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Prefabs 的本地化字符串。
        /// </summary>
        internal static string PrefabGroupName {
            get {
                return ResourceManager.GetString("PrefabGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preview the prototype code without any tag comments  for the selected type. 的本地化字符串。
        /// </summary>
        internal static string PreviewCode {
            get {
                return ResourceManager.GetString("PreviewCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Properties 的本地化字符串。
        /// </summary>
        internal static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Properties of {0} 的本地化字符串。
        /// </summary>
        internal static string PropertiesOf {
            get {
                return ResourceManager.GetString("PropertiesOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please set the right name and type for the property. 的本地化字符串。
        /// </summary>
        internal static string PropertyVerifyWarning {
            get {
                return ResourceManager.GetString("PropertyVerifyWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure remove all selected parameters? 的本地化字符串。
        /// </summary>
        internal static string RemoveParametersInfo {
            get {
                return ResourceManager.GetString("RemoveParametersInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Repeat {
            get {
                object obj = ResourceManager.GetObject("Repeat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap saveall {
            get {
                object obj = ResourceManager.GetObject("saveall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Save as Prefab 的本地化字符串。
        /// </summary>
        internal static string SaveAsPrefab {
            get {
                return ResourceManager.GetString("SaveAsPrefab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save as Reference 的本地化字符串。
        /// </summary>
        internal static string SaveAsReference {
            get {
                return ResourceManager.GetString("SaveAsReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Behavior as 的本地化字符串。
        /// </summary>
        internal static string SaveBehaviorAs {
            get {
                return ResourceManager.GetString("SaveBehaviorAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save Error 的本地化字符串。
        /// </summary>
        internal static string SaveError {
            get {
                return ResourceManager.GetString("SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save as Prefab 的本地化字符串。
        /// </summary>
        internal static string SavePrefab {
            get {
                return ResourceManager.GetString("SavePrefab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save as Reference 的本地化字符串。
        /// </summary>
        internal static string SaveReference {
            get {
                return ResourceManager.GetString("SaveReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Search {
            get {
                object obj = ResourceManager.GetObject("Search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Select Behavior Folder 的本地化字符串。
        /// </summary>
        internal static string SelectBehaviorFolder {
            get {
                return ResourceManager.GetString("SelectBehaviorFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Export Folder 的本地化字符串。
        /// </summary>
        internal static string SelectExportFolder {
            get {
                return ResourceManager.GetString("SelectExportFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Workspace Folder 的本地化字符串。
        /// </summary>
        internal static string SelectWorkspaceFolder {
            get {
                return ResourceManager.GetString("SelectWorkspaceFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select XML Plugins Folder 的本地化字符串。
        /// </summary>
        internal static string SelectXMLPluginsFolder {
            get {
                return ResourceManager.GetString("SelectXMLPluginsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set the C++ header files. 的本地化字符串。
        /// </summary>
        internal static string SetHeaderFiles {
            get {
                return ResourceManager.GetString("SetHeaderFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Choose Meta File 的本地化字符串。
        /// </summary>
        internal static string SetMetaFile {
            get {
                return ResourceManager.GetString("SetMetaFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Skip_backward {
            get {
                object obj = ResourceManager.GetObject("Skip_backward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Skip_forward {
            get {
                object obj = ResourceManager.GetObject("Skip_forward", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Stop {
            get {
                object obj = ResourceManager.GetObject("Stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Stop Analyzing 的本地化字符串。
        /// </summary>
        internal static string StopAnalyzingDump {
            get {
                return ResourceManager.GetString("StopAnalyzingDump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop Analyzing Log File 的本地化字符串。
        /// </summary>
        internal static string StopAnalyzingLog {
            get {
                return ResourceManager.GetString("StopAnalyzingLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} can&apos;t be used as a referened behavior as it&apos;s root is not a Task node. 的本地化字符串。
        /// </summary>
        internal static string SubTreeHasNoTaskError {
            get {
                return ResourceManager.GetString("SubTreeHasNoTaskError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 success 的本地化字符串。
        /// </summary>
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This is a referenced tree. 的本地化字符串。
        /// </summary>
        internal static string ThisIsReferenceTree {
            get {
                return ResourceManager.GetString("ThisIsReferenceTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Transform_move1 {
            get {
                object obj = ResourceManager.GetObject("Transform_move1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Transform_move2 {
            get {
                object obj = ResourceManager.GetObject("Transform_move2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure remove the selected type? 的本地化字符串。
        /// </summary>
        internal static string TypeRemoveWarning {
            get {
                return ResourceManager.GetString("TypeRemoveWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please set the right name for the type. 的本地化字符串。
        /// </summary>
        internal static string TypeVerifyWarning {
            get {
                return ResourceManager.GetString("TypeVerifyWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If using the int value, the Wait node will use int value, else use the double value. 的本地化字符串。
        /// </summary>
        internal static string UseIntValueInfo {
            get {
                return ResourceManager.GetString("UseIntValueInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View 的本地化字符串。
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View Local Variable 的本地化字符串。
        /// </summary>
        internal static string ViewLocalProperty {
            get {
                return ResourceManager.GetString("ViewLocalProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View Property 的本地化字符串。
        /// </summary>
        internal static string ViewProperty {
            get {
                return ResourceManager.GetString("ViewProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The workspace is changed from {0} to {1}. 的本地化字符串。
        /// </summary>
        internal static string WorkspaceChangedInfo {
            get {
                return ResourceManager.GetString("WorkspaceChangedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The behavior file &quot;{0}&quot; can not be found.
        ///
        ///Please be sure to open the workspace which is used by the runtime! 的本地化字符串。
        /// </summary>
        internal static string WorkspaceDebugErrorInfo {
            get {
                return ResourceManager.GetString("WorkspaceDebugErrorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Workspace 的本地化字符串。
        /// </summary>
        internal static string WorkspaceEditTiltle {
            get {
                return ResourceManager.GetString("WorkspaceEditTiltle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Set Workspace Error 的本地化字符串。
        /// </summary>
        internal static string WorkspaceError {
            get {
                return ResourceManager.GetString("WorkspaceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 the workspace and exported behaviors should be in the same drive. 的本地化字符串。
        /// </summary>
        internal static string WorkspaceExportRootWarning {
            get {
                return ResourceManager.GetString("WorkspaceExportRootWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The workspace {0} can not be loaded! 的本地化字符串。
        /// </summary>
        internal static string WorkspaceLoadError {
            get {
                return ResourceManager.GetString("WorkspaceLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please set the name and location for the new workspace! 的本地化字符串。
        /// </summary>
        internal static string WorkspaceNameWarning {
            get {
                return ResourceManager.GetString("WorkspaceNameWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please set the name, workspace location and meta location of the new workspace! 的本地化字符串。
        /// </summary>
        internal static string WorkspaceSettingWarning {
            get {
                return ResourceManager.GetString("WorkspaceSettingWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 the workspace and source behaviors should be in the same drive. 的本地化字符串。
        /// </summary>
        internal static string WorkspaceSourceRootWarning {
            get {
                return ResourceManager.GetString("WorkspaceSourceRootWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The open workspace :
        ///&apos;{0}&apos;
        ///is not the right one used by game:
        ///&apos;{1}&apos; 的本地化字符串。
        /// </summary>
        internal static string WorkspaceWarningInfo {
            get {
                return ResourceManager.GetString("WorkspaceWarningInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 the workspace and xml meta should be in the same drive. 的本地化字符串。
        /// </summary>
        internal static string WorkspaceXmlMetaRootWarning {
            get {
                return ResourceManager.GetString("WorkspaceXmlMetaRootWarning", resourceCulture);
            }
        }
    }
}
